name: build-linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    inputs:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: pwsh "${{github.workspace}}/do-tests.ps1"
